### PR TITLE
Feature/align configs

### PR DESCRIPTION
**Pull request by ghost**
* See Changelog for feature changes.
* Implements #4

### CODE REVIEW

**Comment by ghost** [comment]
@centigrade-kdk Could you have a look on this?

**Review by centigrade-kdk — COMMENTED** [review]
Is there a  reason why we have a yarn.lock and a package-lock.json. If we can choose between one, I would go for package-lock.json.

**Comment by ghost** [comment]
@centigrade-kdk I think yarn.lock was generated by vs-code-yoman generator. Removed yarn.lock with commit https://github.com/Centigrade/centigrade-angular-essentials/pull/5/commits/6ff5d9daa2404399f1d8e489053d128788b1bc12 and went for package-lock.json only.

**Comment by ghost** [comment]
@centigrade-kdk Removed TS Hero, update vs code settings (removed editor rulers, VS code organize on save), update package-lock to fix vulnerability

**Review by centigrade-kdk — APPROVED** [review]
Looks good!

**Pull request merged**
